import pexpect

child = pexpect.spawn("./StartTUI.sh", encoding="utf-8", timeout=None)
child.expect("Enter selection \(default: Next\\):")
child.sendline("")
print("Select the medias you want to install")
child.expect("Select the medias you want to install")
child.expect("Enter selection \(default: Next\):")
child.sendline("0")
child.expect("Enter selection \(default: Next\):")
child.sendline("5")
child.expect("Enter selection \(default: Next\):")
child.sendline("6")
child.expect("Enter selection \(default: Next\):")
child.sendline("7")
child.expect("Enter selection \(default: Next\):")
child.sendline("")
print("SIMULIA 2019 Extended Products")
child.expect("SIMULIA 2019 Extended Products")
child.expect("The installation program has enough information to start.")
child.expect("Enter selection \(default: Install\):")
child.sendline("")
print("3DEXPERIENCE R2019x Abaqus Simulation Services")
child.expect("3DEXPERIENCE R2019x Abaqus Simulation Services")
child.expect("Choose the installation directory:")
child.expect("Default \[/usr/DassaultSystemes/SimulationServices/V6R2019x\]:")
child.sendline("/opt/DassaultSystemes/SimulationServices/V6R2019x")
child.expect("Enter selection \(default: Next\):")
child.sendline("4") # exclude 4
child.expect("Enter selection \(default: Next\):")
child.sendline("")
child.expect("Files will be installed in the following directory:")
child.expect("/opt/DassaultSystemes/SimulationServices/V6R2019x")
child.expect("Enter selection \(default: Install\):")
child.sendline("")
child.expect("The installation program has finished installing 3DEXPERIENCE R2019x on your computer, in /opt/DassaultSystemes/SimulationServices/V6R2019x")
child.expect("Enter selection \(default: Close\):")
child.sendline("")

child.expect("Choose the CODE installation directory to update with CAA API:")
child.expect("Default \[/usr/DassaultSystemes/SimulationServices/V6R2019x\]:")
child.sendline("/opt/DassaultSystemes/SimulationServices/V6R2019x")
child.expect("Enter selection \(default: Next\):")
child.sendline("") # default is All (ODB API Services, Explicit Solver, Standard Solver)
child.expect("Enter selection \(default: Install\):")
child.sendline("")
child.expect("The installation program has finished installing 3DEXPERIENCE R2019x CAA API on your computer, in /opt/DassaultSystemes/SimulationServices/V6R2019x")
child.expect("Enter selection \(default: Close\):")
child.sendline("")

print("SIMULIA Abaqus CAE 2019")
child.expect("SIMULIA Abaqus CAE 2019")
child.expect("Default \[/usr/SIMULIA/CAE/2019\]:")
child.sendline("/opt/SIMULIA/CAE/2019")
child.expect("Enter selection \(default: Next\):")
child.sendline("2") # DSLS
child.expect("Enter selection \(default: Next\):")
child.sendline("")
child.expect("Please enter the hostname or IP address of your DS license server\(s\)")
child.expect("Default \[localhost\]:")
child.sendline("") # Add the host of the license server
child.expect("License Server 2")
child.expect("Default \[\]:")
child.sendline("")
child.expect("License Server 3")
child.expect("Default \[\]:")
child.sendline("")
child.expect("Abaqus solver installation path")
child.expect("Default \[\]:")
child.sendline("/opt/DassaultSystemes/SimulationServices/V6R2019x")
child.expect("Provide the target location for the Abaqus commands directory")
child.expect("Default \[/var/DassaultSystemes/SIMULIA/Commands\]:")
child.sendline("/opt/SIMULIA/Commands")
child.expect("Provide the target location for the Abaqus/CAE external plugins directory.")
child.expect("Default \[/var/DassaultSystemes/SIMULIA/CAE/plugins/2019\]:")
child.sendline("/opt/SIMULIA/CAE/plugins/2019")
child.expect("Documentation Configuration options")
child.expect("Enter selection \(default: Next\):")
child.sendline("4") # skip doc
child.expect("Enter selection \(default: Next\):")
child.sendline("")
child.expect("Files will be installed in the following directory:")
child.expect("/opt/SIMULIA/CAE/2019")
child.expect("License Server Type: DSLS")
child.expect("User-defined Abaqus solver choice: /opt/DassaultSystemes/SimulationServices/V6R2019x")
child.expect("Commands directory path: /opt/SIMULIA/Commands")
child.expect("External plugins directory path: /opt/SIMULIA/CAE/plugins/2019")
child.expect("Enter selection \(default: Install\):")
print("Please be patient;  it will take a few minutes to complete.")
child.sendline("")
child.expect("The installation program has finished installing SIMULIA Abaqus CAE 2019 on your computer, in /opt/SIMULIA/CAE/2019.")
child.expect("Enter selection \(default: Close\):")
child.sendline("")
child.expect("Successful installation:")
child.expect("Enter selection \(default: Close\):")
child.sendline("")
